---
- name: create directory and files
  hosts: localhost
  tasks:

    - name: Install httpd pkg
      yum:
        name: httpd
        state: present

    - name: create web directory
      file:
        path: /web
        state: directory
        group: ansi_user
        mode: '2775'

    - name: create index.html with content
      copy:
        content: "Learning Ansible"
        dest: /web/index.html

    - name: set SELinux context
      sefcontext:
        target: '/web(/.*)?'
        setype: httpd_sys_content_t
        state: present

    - name: apply SELinux context
      command: restorecon -Rv /web

    - name: create link
      file:
        src: /web
        dest: /var/www/html/web
        state: link
