---
- name: User Creation
  hosts: dev,test
  vars_files:
    - user_list.yaml
    - vault.yml

  tasks:
    - name: create group
      group:
        name: opsdev
        state: present

    - name: create user
      when: "item.job == 'developer'"
      user:
        name: "{{item.name}}"
        uid: "{{item.uid}}"
        groups: opsdev
        password: "{{ developer_pw | password_hash('sha512')}}"
        password_expire_max: "{{item.password_expire_days}}"

      loop:
        "{{users}}"


- name: User Creation
  hosts: test
  vars_files:
    - user_list.yaml
    - vault.yml

  tasks:
    - name: create group
      group:
        name: opsmgr
        state: present

    - name: create user
      when: "item.job == 'manager'"
      user:
        name: "{{item.name}}"
        uid: "{{item.uid}}"
        groups: opsmgr
        password: "{{ manager_pw | password_hash('sha512')}}"
        password_expire_max: "{{item.password_expire_days}}"

      loop:
        "{{users}}"
